<?php 

class countryCode
{
 public static $cCode = ['AF' => ['Name' => 'Afghanistan',
'Alpha3' => 'AFG',
'Numeric' => '4',],
'AL' => ['Name' => 'Albania',
'Alpha3' => 'ALB',
'Numeric' => '8',],
'DZ' => ['Name' => 'Algeria',
'Alpha3' => 'DZA',
'Numeric' => '12',],
'AS' => ['Name' => 'American Samoa',
'Alpha3' => 'ASM',
'Numeric' => '16',],
'AD' => ['Name' => 'Andorra',
'Alpha3' => 'AND',
'Numeric' => '20',],
'AO' => ['Name' => 'Angola',
'Alpha3' => 'AGO',
'Numeric' => '24',],
'AI' => ['Name' => 'Anguilla',
'Alpha3' => 'AIA',
'Numeric' => '660',],
'AQ' => ['Name' => 'Antarctica',
'Alpha3' => 'ATA',
'Numeric' => '10',],
'AG' => ['Name' => 'Antigua and Barbuda',
'Alpha3' => 'ATG',
'Numeric' => '28',],
'AR' => ['Name' => 'Argentina',
'Alpha3' => 'ARG',
'Numeric' => '32',],
'AM' => ['Name' => 'Armenia',
'Alpha3' => 'ARM',
'Numeric' => '51',],
'AW' => ['Name' => 'Aruba',
'Alpha3' => 'ABW',
'Numeric' => '533',],
'AU' => ['Name' => 'Australia',
'Alpha3' => 'AUS',
'Numeric' => '36',],
'AT' => ['Name' => 'Austria',
'Alpha3' => 'AUT',
'Numeric' => '40',],
'AZ' => ['Name' => 'Azerbaijan',
'Alpha3' => 'AZE',
'Numeric' => '31',],
'BS' => ['Name' => 'Bahamas',
'Alpha3' => 'BHS',
'Numeric' => '44',],
'BH' => ['Name' => 'Bahrain',
'Alpha3' => 'BHR',
'Numeric' => '48',],
'BD' => ['Name' => 'Bangladesh',
'Alpha3' => 'BGD',
'Numeric' => '50',],
'BB' => ['Name' => 'Barbados',
'Alpha3' => 'BRB',
'Numeric' => '52',],
'BY' => ['Name' => 'Belarus',
'Alpha3' => 'BLR',
'Numeric' => '112',],
'BE' => ['Name' => 'Belgium',
'Alpha3' => 'BEL',
'Numeric' => '56',],
'BZ' => ['Name' => 'Belize',
'Alpha3' => 'BLZ',
'Numeric' => '84',],
'BJ' => ['Name' => 'Benin',
'Alpha3' => 'BEN',
'Numeric' => '204',],
'BM' => ['Name' => 'Bermuda',
'Alpha3' => 'BMU',
'Numeric' => '60',],
'BT' => ['Name' => 'Bhutan',
'Alpha3' => 'BTN',
'Numeric' => '64',],
'BO' => ['Name' => 'Bolivia, Plurinational State of',
'Alpha3' => 'BOL',
'Numeric' => '68',],
'BO' => ['Name' => 'Bolivia',
'Alpha3' => 'BOL',
'Numeric' => '68',],
'BA' => ['Name' => 'Bosnia and Herzegovina',
'Alpha3' => 'BIH',
'Numeric' => '70',],
'BW' => ['Name' => 'Botswana',
'Alpha3' => 'BWA',
'Numeric' => '72',],
'BV' => ['Name' => 'Bouvet Island',
'Alpha3' => 'BVT',
'Numeric' => '74',],
'BR' => ['Name' => 'Brazil',
'Alpha3' => 'BRA',
'Numeric' => '76',],
'IO' => ['Name' => 'British Indian Ocean Territory',
'Alpha3' => 'IOT',
'Numeric' => '86',],
'BN' => ['Name' => 'Brunei Darussalam',
'Alpha3' => 'BRN',
'Numeric' => '96',],
'BN' => ['Name' => 'Brunei',
'Alpha3' => 'BRN',
'Numeric' => '96',],
'BG' => ['Name' => 'Bulgaria',
'Alpha3' => 'BGR',
'Numeric' => '100',],
'BF' => ['Name' => 'Burkina Faso',
'Alpha3' => 'BFA',
'Numeric' => '854',],
'BI' => ['Name' => 'Burundi',
'Alpha3' => 'BDI',
'Numeric' => '108',],
'KH' => ['Name' => 'Cambodia',
'Alpha3' => 'KHM',
'Numeric' => '116',],
'CM' => ['Name' => 'Cameroon',
'Alpha3' => 'CMR',
'Numeric' => '120',],
'CA' => ['Name' => 'Canada',
'Alpha3' => 'CAN',
'Numeric' => '124',],
'CV' => ['Name' => 'Cape Verde',
'Alpha3' => 'CPV',
'Numeric' => '132',],
'KY' => ['Name' => 'Cayman Islands',
'Alpha3' => 'CYM',
'Numeric' => '136',],
'CF' => ['Name' => 'Central African Republic',
'Alpha3' => 'CAF',
'Numeric' => '140',],
'TD' => ['Name' => 'Chad',
'Alpha3' => 'TCD',
'Numeric' => '148',],
'CL' => ['Name' => 'Chile',
'Alpha3' => 'CHL',
'Numeric' => '152',],
'CN' => ['Name' => 'China',
'Alpha3' => 'CHN',
'Numeric' => '156',],
'CX' => ['Name' => 'Christmas Island',
'Alpha3' => 'CXR',
'Numeric' => '162',],
'CC' => ['Name' => 'Cocos (Keeling) Islands',
'Alpha3' => 'CCK',
'Numeric' => '166',],
'CO' => ['Name' => 'Colombia',
'Alpha3' => 'COL',
'Numeric' => '170',],
'KM' => ['Name' => 'Comoros',
'Alpha3' => 'COM',
'Numeric' => '174',],
'CG' => ['Name' => 'Congo',
'Alpha3' => 'COG',
'Numeric' => '178',],
'CD' => ['Name' => 'Congo, the Democratic Republic of the',
'Alpha3' => 'COD',
'Numeric' => '180',],
'CK' => ['Name' => 'Cook Islands',
'Alpha3' => 'COK',
'Numeric' => '184',],
'CR' => ['Name' => 'Costa Rica',
'Alpha3' => 'CRI',
'Numeric' => '188',],
'CI' => ['Name' => 'Côte dIvoire',
'Alpha3' => 'CIV',
'Numeric' => '384',],
'CI' => ['Name' => 'Ivory Coast',
'Alpha3' => 'CIV',
'Numeric' => '384',],
'HR' => ['Name' => 'Croatia',
'Alpha3' => 'HRV',
'Numeric' => '191',],
'CU' => ['Name' => 'Cuba',
'Alpha3' => 'CUB',
'Numeric' => '192',],
'CY' => ['Name' => 'Cyprus',
'Alpha3' => 'CYP',
'Numeric' => '196',],
'CZ' => ['Name' => 'Czech Republic',
'Alpha3' => 'CZE',
'Numeric' => '203',],
'DK' => ['Name' => 'Denmark',
'Alpha3' => 'DNK',
'Numeric' => '208',],
'DJ' => ['Name' => 'Djibouti',
'Alpha3' => 'DJI',
'Numeric' => '262',],
'DM' => ['Name' => 'Dominica',
'Alpha3' => 'DMA',
'Numeric' => '212',],
'DO' => ['Name' => 'Dominican Republic',
'Alpha3' => 'DOM',
'Numeric' => '214',],
'EC' => ['Name' => 'Ecuador',
'Alpha3' => 'ECU',
'Numeric' => '218',],
'EG' => ['Name' => 'Egypt',
'Alpha3' => 'EGY',
'Numeric' => '818',],
'SV' => ['Name' => 'El Salvador',
'Alpha3' => 'SLV',
'Numeric' => '222',],
'GQ' => ['Name' => 'Equatorial Guinea',
'Alpha3' => 'GNQ',
'Numeric' => '226',],
'ER' => ['Name' => 'Eritrea',
'Alpha3' => 'ERI',
'Numeric' => '232',],
'EE' => ['Name' => 'Estonia',
'Alpha3' => 'EST',
'Numeric' => '233',],
'ET' => ['Name' => 'Ethiopia',
'Alpha3' => 'ETH',
'Numeric' => '231',],
'FK' => ['Name' => 'Falkland Islands (Malvinas)',
'Alpha3' => 'FLK',
'Numeric' => '238',],
'FO' => ['Name' => 'Faroe Islands',
'Alpha3' => 'FRO',
'Numeric' => '234',],
'FJ' => ['Name' => 'Fiji',
'Alpha3' => 'FJI',
'Numeric' => '242',],
'FI' => ['Name' => 'Finland',
'Alpha3' => 'FIN',
'Numeric' => '246',],
'FR' => ['Name' => 'France',
'Alpha3' => 'FRA',
'Numeric' => '250',],
'GF' => ['Name' => 'French Guiana',
'Alpha3' => 'GUF',
'Numeric' => '254',],
'PF' => ['Name' => 'French Polynesia',
'Alpha3' => 'PYF',
'Numeric' => '258',],
'TF' => ['Name' => 'French Southern Territories',
'Alpha3' => 'ATF',
'Numeric' => '260',],
'GA' => ['Name' => 'Gabon',
'Alpha3' => 'GAB',
'Numeric' => '266',],
'GM' => ['Name' => 'Gambia',
'Alpha3' => 'GMB',
'Numeric' => '270',],
'GE' => ['Name' => 'Georgia',
'Alpha3' => 'GEO',
'Numeric' => '268',],
'DE' => ['Name' => 'Germany',
'Alpha3' => 'DEU',
'Numeric' => '276',],
'GH' => ['Name' => 'Ghana',
'Alpha3' => 'GHA',
'Numeric' => '288',],
'GI' => ['Name' => 'Gibraltar',
'Alpha3' => 'GIB',
'Numeric' => '292',],
'GR' => ['Name' => 'Greece',
'Alpha3' => 'GRC',
'Numeric' => '300',],
'GL' => ['Name' => 'Greenland',
'Alpha3' => 'GRL',
'Numeric' => '304',],
'GD' => ['Name' => 'Grenada',
'Alpha3' => 'GRD',
'Numeric' => '308',],
'GP' => ['Name' => 'Guadeloupe',
'Alpha3' => 'GLP',
'Numeric' => '312',],
'GU' => ['Name' => 'Guam',
'Alpha3' => 'GUM',
'Numeric' => '316',],
'GT' => ['Name' => 'Guatemala',
'Alpha3' => 'GTM',
'Numeric' => '320',],
'GG' => ['Name' => 'Guernsey',
'Alpha3' => 'GGY',
'Numeric' => '831',],
'GN' => ['Name' => 'Guinea',
'Alpha3' => 'GIN',
'Numeric' => '324',],
'GW' => ['Name' => 'Guinea-Bissau',
'Alpha3' => 'GNB',
'Numeric' => '624',],
'GY' => ['Name' => 'Guyana',
'Alpha3' => 'GUY',
'Numeric' => '328',],
'HT' => ['Name' => 'Haiti',
'Alpha3' => 'HTI',
'Numeric' => '332',],
'HM' => ['Name' => 'Heard Island and McDonald Islands',
'Alpha3' => 'HMD',
'Numeric' => '334',],
'VA' => ['Name' => 'Holy See (Vatican City State)',
'Alpha3' => 'VAT',
'Numeric' => '336',],
'HN' => ['Name' => 'Honduras',
'Alpha3' => 'HND',
'Numeric' => '340',],
'HK' => ['Name' => 'Hong Kong',
'Alpha3' => 'HKG',
'Numeric' => '344',],
'HU' => ['Name' => 'Hungary',
'Alpha3' => 'HUN',
'Numeric' => '348',],
'IS' => ['Name' => 'Iceland',
'Alpha3' => 'ISL',
'Numeric' => '352',],
'IN' => ['Name' => 'India',
'Alpha3' => 'IND',
'Numeric' => '356',],
'ID' => ['Name' => 'Indonesia',
'Alpha3' => 'IDN',
'Numeric' => '360',],
'IR' => ['Name' => 'Iran, Islamic Republic of',
'Alpha3' => 'IRN',
'Numeric' => '364',],
'IQ' => ['Name' => 'Iraq',
'Alpha3' => 'IRQ',
'Numeric' => '368',],
'IE' => ['Name' => 'Ireland',
'Alpha3' => 'IRL',
'Numeric' => '372',],
'IM' => ['Name' => 'Isle of Man',
'Alpha3' => 'IMN',
'Numeric' => '833',],
'IL' => ['Name' => 'Israel',
'Alpha3' => 'ISR',
'Numeric' => '376',],
'IT' => ['Name' => 'Italy',
'Alpha3' => 'ITA',
'Numeric' => '380',],
'JM' => ['Name' => 'Jamaica',
'Alpha3' => 'JAM',
'Numeric' => '388',],
'JP' => ['Name' => 'Japan',
'Alpha3' => 'JPN',
'Numeric' => '392',],
'JE' => ['Name' => 'Jersey',
'Alpha3' => 'JEY',
'Numeric' => '832',],
'JO' => ['Name' => 'Jordan',
'Alpha3' => 'JOR',
'Numeric' => '400',],
'KZ' => ['Name' => 'Kazakhstan',
'Alpha3' => 'KAZ',
'Numeric' => '398',],
'KE' => ['Name' => 'Kenya',
'Alpha3' => 'KEN',
'Numeric' => '404',],
'KI' => ['Name' => 'Kiribati',
'Alpha3' => 'KIR',
'Numeric' => '296',],
'KP' => ['Name' => 'Korea, Democratic People\'s Republic of',
'Alpha3' => 'PRK',
'Numeric' => '408',],
'KR' => ['Name' => 'Korea, Republic of',
'Alpha3' => 'KOR',
'Numeric' => '410',],
'KR' => ['Name' => 'South Korea',
'Alpha3' => 'KOR',
'Numeric' => '410',],
'KW' => ['Name' => 'Kuwait',
'Alpha3' => 'KWT',
'Numeric' => '414',],
'KG' => ['Name' => 'Kyrgyzstan',
'Alpha3' => 'KGZ',
'Numeric' => '417',],
'LA' => ['Name' => 'Lao People\'s Democratic Republic',
'Alpha3' => 'LAO',
'Numeric' => '418',],
'LV' => ['Name' => 'Latvia',
'Alpha3' => 'LVA',
'Numeric' => '428',],
'LB' => ['Name' => 'Lebanon',
'Alpha3' => 'LBN',
'Numeric' => '422',],
'LS' => ['Name' => 'Lesotho',
'Alpha3' => 'LSO',
'Numeric' => '426',],
'LR' => ['Name' => 'Liberia',
'Alpha3' => 'LBR',
'Numeric' => '430',],
'LY' => ['Name' => 'Libyan Arab Jamahiriya',
'Alpha3' => 'LBY',
'Numeric' => '434',],
'LY' => ['Name' => 'Libya',
'Alpha3' => 'LBY',
'Numeric' => '434',],
'LI' => ['Name' => 'Liechtenstein',
'Alpha3' => 'LIE',
'Numeric' => '438',],
'LT' => ['Name' => 'Lithuania',
'Alpha3' => 'LTU',
'Numeric' => '440',],
'LU' => ['Name' => 'Luxembourg',
'Alpha3' => 'LUX',
'Numeric' => '442',],
'MO' => ['Name' => 'Macao',
'Alpha3' => 'MAC',
'Numeric' => '446',],
'MK' => ['Name' => 'Macedonia, the former Yugoslav Republic of',
'Alpha3' => 'MKD',
'Numeric' => '807',],
'MG' => ['Name' => 'Madagascar',
'Alpha3' => 'MDG',
'Numeric' => '450',],
'MW' => ['Name' => 'Malawi',
'Alpha3' => 'MWI',
'Numeric' => '454',],
'MY' => ['Name' => 'Malaysia',
'Alpha3' => 'MYS',
'Numeric' => '458',],
'MV' => ['Name' => 'Maldives',
'Alpha3' => 'MDV',
'Numeric' => '462',],
'ML' => ['Name' => 'Mali',
'Alpha3' => 'MLI',
'Numeric' => '466',],
'MT' => ['Name' => 'Malta',
'Alpha3' => 'MLT',
'Numeric' => '470',],
'MH' => ['Name' => 'Marshall Islands',
'Alpha3' => 'MHL',
'Numeric' => '584',],
'MQ' => ['Name' => 'Martinique',
'Alpha3' => 'MTQ',
'Numeric' => '474',],
'MR' => ['Name' => 'Mauritania',
'Alpha3' => 'MRT',
'Numeric' => '478',],
'MU' => ['Name' => 'Mauritius',
'Alpha3' => 'MUS',
'Numeric' => '480',],
'YT' => ['Name' => 'Mayotte',
'Alpha3' => 'MYT',
'Numeric' => '175',],
'MX' => ['Name' => 'Mexico',
'Alpha3' => 'MEX',
'Numeric' => '484',],
'FM' => ['Name' => 'Micronesia, Federated States of',
'Alpha3' => 'FSM',
'Numeric' => '583',],
'MD' => ['Name' => 'Moldova, Republic of',
'Alpha3' => 'MDA',
'Numeric' => '498',],
'MC' => ['Name' => 'Monaco',
'Alpha3' => 'MCO',
'Numeric' => '492',],
'MN' => ['Name' => 'Mongolia',
'Alpha3' => 'MNG',
'Numeric' => '496',],
'ME' => ['Name' => 'Montenegro',
'Alpha3' => 'MNE',
'Numeric' => '499',],
'MS' => ['Name' => 'Montserrat',
'Alpha3' => 'MSR',
'Numeric' => '500',],
'MA' => ['Name' => 'Morocco',
'Alpha3' => 'MAR',
'Numeric' => '504',],
'MZ' => ['Name' => 'Mozambique',
'Alpha3' => 'MOZ',
'Numeric' => '508',],
'MM' => ['Name' => 'Myanmar',
'Alpha3' => 'MMR',
'Numeric' => '104',],
'MM' => ['Name' => 'Burma',
'Alpha3' => 'MMR',
'Numeric' => '104',],
'NA' => ['Name' => 'Namibia',
'Alpha3' => 'NAM',
'Numeric' => '516',],
'NR' => ['Name' => 'Nauru',
'Alpha3' => 'NRU',
'Numeric' => '520',],
'NP' => ['Name' => 'Nepal',
'Alpha3' => 'NPL',
'Numeric' => '524',],
'NL' => ['Name' => 'Netherlands',
'Alpha3' => 'NLD',
'Numeric' => '528',],
'AN' => ['Name' => 'Netherlands Antilles',
'Alpha3' => 'ANT',
'Numeric' => '530',],
'NC' => ['Name' => 'New Caledonia',
'Alpha3' => 'NCL',
'Numeric' => '540',],
'NZ' => ['Name' => 'New Zealand',
'Alpha3' => 'NZL',
'Numeric' => '554',],
'NI' => ['Name' => 'Nicaragua',
'Alpha3' => 'NIC',
'Numeric' => '558',],
'NE' => ['Name' => 'Niger',
'Alpha3' => 'NER',
'Numeric' => '562',],
'NG' => ['Name' => 'Nigeria',
'Alpha3' => 'NGA',
'Numeric' => '566',],
'NU' => ['Name' => 'Niue',
'Alpha3' => 'NIU',
'Numeric' => '570',],
'NF' => ['Name' => 'Norfolk Island',
'Alpha3' => 'NFK',
'Numeric' => '574',],
'MP' => ['Name' => 'Northern Mariana Islands',
'Alpha3' => 'MNP',
'Numeric' => '580',],
'NO' => ['Name' => 'Norway',
'Alpha3' => 'NOR',
'Numeric' => '578',],
'OM' => ['Name' => 'Oman',
'Alpha3' => 'OMN',
'Numeric' => '512',],
'PK' => ['Name' => 'Pakistan',
'Alpha3' => 'PAK',
'Numeric' => '586',],
'PW' => ['Name' => 'Palau',
'Alpha3' => 'PLW',
'Numeric' => '585',],
'PS' => ['Name' => 'Palestinian Territory, Occupied',
'Alpha3' => 'PSE',
'Numeric' => '275',],
'PA' => ['Name' => 'Panama',
'Alpha3' => 'PAN',
'Numeric' => '591',],
'PG' => ['Name' => 'Papua New Guinea',
'Alpha3' => 'PNG',
'Numeric' => '598',],
'PY' => ['Name' => 'Paraguay',
'Alpha3' => 'PRY',
'Numeric' => '600',],
'PE' => ['Name' => 'Peru',
'Alpha3' => 'PER',
'Numeric' => '604',],
'PH' => ['Name' => 'Philippines',
'Alpha3' => 'PHL',
'Numeric' => '608',],
'PN' => ['Name' => 'Pitcairn',
'Alpha3' => 'PCN',
'Numeric' => '612',],
'PL' => ['Name' => 'Poland',
'Alpha3' => 'POL',
'Numeric' => '616',],
'PT' => ['Name' => 'Portugal',
'Alpha3' => 'PRT',
'Numeric' => '620',],
'PR' => ['Name' => 'Puerto Rico',
'Alpha3' => 'PRI',
'Numeric' => '630',],
'QA' => ['Name' => 'Qatar',
'Alpha3' => 'QAT',
'Numeric' => '634',],
'RE' => ['Name' => 'Réunion',
'Alpha3' => 'REU',
'Numeric' => '638',],
'RO' => ['Name' => 'Romania',
'Alpha3' => 'ROU',
'Numeric' => '642',],
'RU' => ['Name' => 'Russian Federation',
'Alpha3' => 'RUS',
'Numeric' => '643',],
'RU' => ['Name' => 'Russia',
'Alpha3' => 'RUS',
'Numeric' => '643',],
'RW' => ['Name' => 'Rwanda',
'Alpha3' => 'RWA',
'Numeric' => '646',],
'SH' => ['Name' => 'Saint Helena, Ascension and Tristan da Cunha',
'Alpha3' => 'SHN',
'Numeric' => '654',],
'KN' => ['Name' => 'Saint Kitts and Nevis',
'Alpha3' => 'KNA',
'Numeric' => '659',],
'LC' => ['Name' => 'Saint Lucia',
'Alpha3' => 'LCA',
'Numeric' => '662',],
'PM' => ['Name' => 'Saint Pierre and Miquelon',
'Alpha3' => 'SPM',
'Numeric' => '666',],
'VC' => ['Name' => 'Saint Vincent and the Grenadines',
'Alpha3' => 'VCT',
'Numeric' => '670',],
'VC' => ['Name' => 'Saint Vincent & the Grenadines',
'Alpha3' => 'VCT',
'Numeric' => '670',],
'VC' => ['Name' => 'St. Vincent and the Grenadines',
'Alpha3' => 'VCT',
'Numeric' => '670',],
'WS' => ['Name' => 'Samoa',
'Alpha3' => 'WSM',
'Numeric' => '882',],
'SM' => ['Name' => 'San Marino',
'Alpha3' => 'SMR',
'Numeric' => '674',],
'ST' => ['Name' => 'Sao Tome and Principe',
'Alpha3' => 'STP',
'Numeric' => '678',],
'SA' => ['Name' => 'Saudi Arabia',
'Alpha3' => 'SAU',
'Numeric' => '682',],
'SN' => ['Name' => 'Senegal',
'Alpha3' => 'SEN',
'Numeric' => '686',],
'RS' => ['Name' => 'Serbia',
'Alpha3' => 'SRB',
'Numeric' => '688',],
'SC' => ['Name' => 'Seychelles',
'Alpha3' => 'SYC',
'Numeric' => '690',],
'SL' => ['Name' => 'Sierra Leone',
'Alpha3' => 'SLE',
'Numeric' => '694',],
'SG' => ['Name' => 'Singapore',
'Alpha3' => 'SGP',
'Numeric' => '702',],
'SK' => ['Name' => 'Slovakia',
'Alpha3' => 'SVK',
'Numeric' => '703',],
'SI' => ['Name' => 'Slovenia',
'Alpha3' => 'SVN',
'Numeric' => '705',],
'SB' => ['Name' => 'Solomon Islands',
'Alpha3' => 'SLB',
'Numeric' => '90',],
'SO' => ['Name' => 'Somalia',
'Alpha3' => 'SOM',
'Numeric' => '706',],
'ZA' => ['Name' => 'South Africa',
'Alpha3' => 'ZAF',
'Numeric' => '710',],
'GS' => ['Name' => 'South Georgia and the South Sandwich Islands',
'Alpha3' => 'SGS',
'Numeric' => '239',],
'SS' => ['Name' => 'South Sudan',
'Alpha3' => 'SSD',
'Numeric' => '728',],
'ES' => ['Name' => 'Spain',
'Alpha3' => 'ESP',
'Numeric' => '724',],
'LK' => ['Name' => 'Sri Lanka',
'Alpha3' => 'LKA',
'Numeric' => '144',],
'SD' => ['Name' => 'Sudan',
'Alpha3' => 'SDN',
'Numeric' => '736',],
'SR' => ['Name' => 'Suriname',
'Alpha3' => 'SUR',
'Numeric' => '740',],
'SJ' => ['Name' => 'Svalbard and Jan Mayen',
'Alpha3' => 'SJM',
'Numeric' => '744',],
'SZ' => ['Name' => 'Swaziland',
'Alpha3' => 'SWZ',
'Numeric' => '748',],
'SE' => ['Name' => 'Sweden',
'Alpha3' => 'SWE',
'Numeric' => '752',],
'CH' => ['Name' => 'Switzerland',
'Alpha3' => 'CHE',
'Numeric' => '756',],
'SY' => ['Name' => 'Syrian Arab Republic',
'Alpha3' => 'SYR',
'Numeric' => '760',],
'TW' => ['Name' => 'Taiwan, Province of China',
'Alpha3' => 'TWN',
'Numeric' => '158',],
'TW' => ['Name' => 'Taiwan',
'Alpha3' => 'TWN',
'Numeric' => '158',],
'TJ' => ['Name' => 'Tajikistan',
'Alpha3' => 'TJK',
'Numeric' => '762',],
'TZ' => ['Name' => 'Tanzania, United Republic of',
'Alpha3' => 'TZA',
'Numeric' => '834',],
'TH' => ['Name' => 'Thailand',
'Alpha3' => 'THA',
'Numeric' => '764',],
'TL' => ['Name' => 'Timor-Leste',
'Alpha3' => 'TLS',
'Numeric' => '626',],
'TG' => ['Name' => 'Togo',
'Alpha3' => 'TGO',
'Numeric' => '768',],
'TK' => ['Name' => 'Tokelau',
'Alpha3' => 'TKL',
'Numeric' => '772',],
'TO' => ['Name' => 'Tonga',
'Alpha3' => 'TON',
'Numeric' => '776',],
'TT' => ['Name' => 'Trinidad and Tobago',
'Alpha3' => 'TTO',
'Numeric' => '780',],
'TN' => ['Name' => 'Tunisia',
'Alpha3' => 'TUN',
'Numeric' => '788',],
'TR' => ['Name' => 'Turkey',
'Alpha3' => 'TUR',
'Numeric' => '792',],
'TM' => ['Name' => 'Turkmenistan',
'Alpha3' => 'TKM',
'Numeric' => '795',],
'TC' => ['Name' => 'Turks and Caicos Islands',
'Alpha3' => 'TCA',
'Numeric' => '796',],
'TV' => ['Name' => 'Tuvalu',
'Alpha3' => 'TUV',
'Numeric' => '798',],
'UG' => ['Name' => 'Uganda',
'Alpha3' => 'UGA',
'Numeric' => '800',],
'UA' => ['Name' => 'Ukraine',
'Alpha3' => 'UKR',
'Numeric' => '804',],
'AE' => ['Name' => 'United Arab Emirates',
'Alpha3' => 'ARE',
'Numeric' => '784',],
'GB' => ['Name' => 'United Kingdom',
'Alpha3' => 'GBR',
'Numeric' => '826',],
'US' => ['Name' => 'United States',
'Alpha3' => 'USA',
'Numeric' => '840',],
'UM' => ['Name' => 'United States Minor Outlying Islands',
'Alpha3' => 'UMI',
'Numeric' => '581',],
'UY' => ['Name' => 'Uruguay',
'Alpha3' => 'URY',
'Numeric' => '858',],
'UZ' => ['Name' => 'Uzbekistan',
'Alpha3' => 'UZB',
'Numeric' => '860',],
'VU' => ['Name' => 'Vanuatu',
'Alpha3' => 'VUT',
'Numeric' => '548',],
'VE' => ['Name' => 'Venezuela, Bolivarian Republic of',
'Alpha3' => 'VEN',
'Numeric' => '862',],
'VE' => ['Name' => 'Venezuela',
'Alpha3' => 'VEN',
'Numeric' => '862',],
'VN' => ['Name' => 'Viet Nam',
'Alpha3' => 'VNM',
'Numeric' => '704',],
'VN' => ['Name' => 'Vietnam',
'Alpha3' => 'VNM',
'Numeric' => '704',],
'VG' => ['Name' => 'Virgin Islands, British',
'Alpha3' => 'VGB',
'Numeric' => '92',],
'VI' => ['Name' => 'Virgin Islands, U.S.',
'Alpha3' => 'VIR',
'Numeric' => '850',],
'WF' => ['Name' => 'Wallis and Futuna',
'Alpha3' => 'WLF',
'Numeric' => '876',],
'EH' => ['Name' => 'Western Sahara',
'Alpha3' => 'ESH',
'Numeric' => '732',],
'YE' => ['Name' => 'Yemen',
'Alpha3' => 'YEM',
'Numeric' => '887',],
'ZM' => ['Name' => 'Zambia',
'Alpha3' => 'ZMB',
'Numeric' => '894',],
'ZW' => ['Name' => 'Zimbabwe',
'Alpha3' => 'ZWE',
'Numeric' => '716',]];
}