USE `YourSchemaHere`;

CREATE TABLE `country_code` (
  `Numeric` int(11) NOT NULL,
  `Country` varchar(300) NOT NULL,
  `Alpha2` varchar(2) DEFAULT NULL,
  `Alpha3` varchar(3) DEFAULT NULL,
  PRIMARY KEY (`Country`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (4,'Afghanistan','AF','AFG');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (8,'Albania','AL','ALB');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (12,'Algeria','DZ','DZA');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (16,'American Samoa','AS','ASM');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (20,'Andorra','AD','AND');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (24,'Angola','AO','AGO');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (660,'Anguilla','AI','AIA');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (10,'Antarctica','AQ','ATA');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (28,'Antigua and Barbuda','AG','ATG');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (32,'Argentina','AR','ARG');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (51,'Armenia','AM','ARM');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (533,'Aruba','AW','ABW');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (36,'Australia','AU','AUS');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (40,'Austria','AT','AUT');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (31,'Azerbaijan','AZ','AZE');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (44,'Bahamas','BS','BHS');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (48,'Bahrain','BH','BHR');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (50,'Bangladesh','BD','BGD');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (52,'Barbados','BB','BRB');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (112,'Belarus','BY','BLR');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (56,'Belgium','BE','BEL');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (84,'Belize','BZ','BLZ');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (204,'Benin','BJ','BEN');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (60,'Bermuda','BM','BMU');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (64,'Bhutan','BT','BTN');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (68,'Bolivia','BO','BOL');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (68,'Bolivia, Plurinational State of','BO','BOL');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (70,'Bosnia and Herzegovina','BA','BIH');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (72,'Botswana','BW','BWA');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (74,'Bouvet Island','BV','BVT');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (76,'Brazil','BR','BRA');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (86,'British Indian Ocean Territory','IO','IOT');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (96,'Brunei','BN','BRN');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (96,'Brunei Darussalam','BN','BRN');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (100,'Bulgaria','BG','BGR');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (854,'Burkina Faso','BF','BFA');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (104,'Burma','MM','MMR');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (108,'Burundi','BI','BDI');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (116,'Cambodia','KH','KHM');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (120,'Cameroon','CM','CMR');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (124,'Canada','CA','CAN');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (132,'Cape Verde','CV','CPV');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (136,'Cayman Islands','KY','CYM');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (140,'Central African Republic','CF','CAF');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (148,'Chad','TD','TCD');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (152,'Chile','CL','CHL');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (156,'China','CN','CHN');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (162,'Christmas Island','CX','CXR');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (166,'Cocos (Keeling) Islands','CC','CCK');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (170,'Colombia','CO','COL');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (174,'Comoros','KM','COM');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (178,'Congo','CG','COG');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (180,'Congo, the Democratic Republic of the','CD','COD');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (184,'Cook Islands','CK','COK');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (188,'Costa Rica','CR','CRI');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (384,'Côte d\'Ivoire','CI','CIV');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (191,'Croatia','HR','HRV');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (192,'Cuba','CU','CUB');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (196,'Cyprus','CY','CYP');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (203,'Czech Republic','CZ','CZE');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (208,'Denmark','DK','DNK');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (262,'Djibouti','DJ','DJI');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (212,'Dominica','DM','DMA');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (214,'Dominican Republic','DO','DOM');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (218,'Ecuador','EC','ECU');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (818,'Egypt','EG','EGY');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (222,'El Salvador','SV','SLV');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (226,'Equatorial Guinea','GQ','GNQ');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (232,'Eritrea','ER','ERI');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (233,'Estonia','EE','EST');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (231,'Ethiopia','ET','ETH');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (238,'Falkland Islands (Malvinas)','FK','FLK');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (234,'Faroe Islands','FO','FRO');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (242,'Fiji','FJ','FJI');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (246,'Finland','FI','FIN');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (250,'France','FR','FRA');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (254,'French Guiana','GF','GUF');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (258,'French Polynesia','PF','PYF');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (260,'French Southern Territories','TF','ATF');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (266,'Gabon','GA','GAB');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (270,'Gambia','GM','GMB');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (268,'Georgia','GE','GEO');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (276,'Germany','DE','DEU');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (288,'Ghana','GH','GHA');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (292,'Gibraltar','GI','GIB');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (300,'Greece','GR','GRC');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (304,'Greenland','GL','GRL');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (308,'Grenada','GD','GRD');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (312,'Guadeloupe','GP','GLP');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (316,'Guam','GU','GUM');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (320,'Guatemala','GT','GTM');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (831,'Guernsey','GG','GGY');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (324,'Guinea','GN','GIN');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (624,'Guinea-Bissau','GW','GNB');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (328,'Guyana','GY','GUY');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (332,'Haiti','HT','HTI');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (334,'Heard Island and McDonald Islands','HM','HMD');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (336,'Holy See (Vatican City State)','VA','VAT');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (340,'Honduras','HN','HND');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (344,'Hong Kong','HK','HKG');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (348,'Hungary','HU','HUN');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (352,'Iceland','IS','ISL');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (356,'India','IN','IND');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (360,'Indonesia','ID','IDN');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (364,'Iran, Islamic Republic of','IR','IRN');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (368,'Iraq','IQ','IRQ');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (372,'Ireland','IE','IRL');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (833,'Isle of Man','IM','IMN');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (376,'Israel','IL','ISR');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (380,'Italy','IT','ITA');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (384,'Ivory Coast','CI','CIV');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (388,'Jamaica','JM','JAM');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (392,'Japan','JP','JPN');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (832,'Jersey','JE','JEY');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (400,'Jordan','JO','JOR');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (398,'Kazakhstan','KZ','KAZ');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (404,'Kenya','KE','KEN');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (296,'Kiribati','KI','KIR');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (408,'Korea, Democratic People\'s Republic of','KP','PRK');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (410,'Korea, Republic of','KR','KOR');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (414,'Kuwait','KW','KWT');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (417,'Kyrgyzstan','KG','KGZ');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (418,'Lao People\'s Democratic Republic','LA','LAO');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (428,'Latvia','LV','LVA');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (422,'Lebanon','LB','LBN');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (426,'Lesotho','LS','LSO');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (430,'Liberia','LR','LBR');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (434,'Libya','LY','LBY');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (434,'Libyan Arab Jamahiriya','LY','LBY');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (438,'Liechtenstein','LI','LIE');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (440,'Lithuania','LT','LTU');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (442,'Luxembourg','LU','LUX');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (446,'Macao','MO','MAC');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (807,'Macedonia, the former Yugoslav Republic of','MK','MKD');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (450,'Madagascar','MG','MDG');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (454,'Malawi','MW','MWI');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (458,'Malaysia','MY','MYS');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (462,'Maldives','MV','MDV');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (466,'Mali','ML','MLI');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (470,'Malta','MT','MLT');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (584,'Marshall Islands','MH','MHL');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (474,'Martinique','MQ','MTQ');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (478,'Mauritania','MR','MRT');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (480,'Mauritius','MU','MUS');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (175,'Mayotte','YT','MYT');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (484,'Mexico','MX','MEX');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (583,'Micronesia, Federated States of','FM','FSM');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (498,'Moldova, Republic of','MD','MDA');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (492,'Monaco','MC','MCO');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (496,'Mongolia','MN','MNG');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (499,'Montenegro','ME','MNE');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (500,'Montserrat','MS','MSR');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (504,'Morocco','MA','MAR');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (508,'Mozambique','MZ','MOZ');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (104,'Myanmar','MM','MMR');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (516,'Namibia','NA','NAM');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (520,'Nauru','NR','NRU');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (524,'Nepal','NP','NPL');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (528,'Netherlands','NL','NLD');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (530,'Netherlands Antilles','AN','ANT');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (540,'New Caledonia','NC','NCL');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (554,'New Zealand','NZ','NZL');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (558,'Nicaragua','NI','NIC');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (562,'Niger','NE','NER');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (566,'Nigeria','NG','NGA');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (570,'Niue','NU','NIU');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (574,'Norfolk Island','NF','NFK');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (580,'Northern Mariana Islands','MP','MNP');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (578,'Norway','NO','NOR');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (512,'Oman','OM','OMN');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (586,'Pakistan','PK','PAK');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (585,'Palau','PW','PLW');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (275,'Palestinian Territory, Occupied','PS','PSE');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (591,'Panama','PA','PAN');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (598,'Papua New Guinea','PG','PNG');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (600,'Paraguay','PY','PRY');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (604,'Peru','PE','PER');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (608,'Philippines','PH','PHL');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (612,'Pitcairn','PN','PCN');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (616,'Poland','PL','POL');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (620,'Portugal','PT','PRT');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (630,'Puerto Rico','PR','PRI');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (634,'Qatar','QA','QAT');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (638,'Réunion','RE','REU');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (642,'Romania','RO','ROU');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (643,'Russia','RU','RUS');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (643,'Russian Federation','RU','RUS');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (646,'Rwanda','RW','RWA');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (654,'Saint Helena, Ascension and Tristan da Cunha','SH','SHN');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (659,'Saint Kitts and Nevis','KN','KNA');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (662,'Saint Lucia','LC','LCA');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (666,'Saint Pierre and Miquelon','PM','SPM');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (670,'Saint Vincent & the Grenadines','VC','VCT');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (670,'Saint Vincent and the Grenadines','VC','VCT');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (882,'Samoa','WS','WSM');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (674,'San Marino','SM','SMR');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (678,'Sao Tome and Principe','ST','STP');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (682,'Saudi Arabia','SA','SAU');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (686,'Senegal','SN','SEN');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (688,'Serbia','RS','SRB');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (690,'Seychelles','SC','SYC');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (694,'Sierra Leone','SL','SLE');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (702,'Singapore','SG','SGP');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (703,'Slovakia','SK','SVK');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (705,'Slovenia','SI','SVN');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (90,'Solomon Islands','SB','SLB');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (706,'Somalia','SO','SOM');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (710,'South Africa','ZA','ZAF');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (239,'South Georgia and the South Sandwich Islands','GS','SGS');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (410,'South Korea','KR','KOR');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (728,'South Sudan','SS','SSD');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (724,'Spain','ES','ESP');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (144,'Sri Lanka','LK','LKA');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (670,'St. Vincent and the Grenadines','VC','VCT');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (736,'Sudan','SD','SDN');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (740,'Suriname','SR','SUR');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (744,'Svalbard and Jan Mayen','SJ','SJM');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (748,'Swaziland','SZ','SWZ');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (752,'Sweden','SE','SWE');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (756,'Switzerland','CH','CHE');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (760,'Syrian Arab Republic','SY','SYR');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (158,'Taiwan','TW','TWN');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (158,'Taiwan, Province of China','TW','TWN');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (762,'Tajikistan','TJ','TJK');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (834,'Tanzania, United Republic of','TZ','TZA');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (764,'Thailand','TH','THA');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (626,'Timor-Leste','TL','TLS');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (768,'Togo','TG','TGO');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (772,'Tokelau','TK','TKL');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (776,'Tonga','TO','TON');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (780,'Trinidad and Tobago','TT','TTO');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (788,'Tunisia','TN','TUN');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (792,'Turkey','TR','TUR');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (795,'Turkmenistan','TM','TKM');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (796,'Turks and Caicos Islands','TC','TCA');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (798,'Tuvalu','TV','TUV');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (800,'Uganda','UG','UGA');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (804,'Ukraine','UA','UKR');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (784,'United Arab Emirates','AE','ARE');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (826,'United Kingdom','GB','GBR');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (840,'United States','US','USA');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (581,'United States Minor Outlying Islands','UM','UMI');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (858,'Uruguay','UY','URY');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (860,'Uzbekistan','UZ','UZB');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (548,'Vanuatu','VU','VUT');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (862,'Venezuela','VE','VEN');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (862,'Venezuela, Bolivarian Republic of','VE','VEN');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (704,'Viet Nam','VN','VNM');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (704,'Vietnam','VN','VNM');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (92,'Virgin Islands, British','VG','VGB');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (850,'Virgin Islands, U.S.','VI','VIR');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (876,'Wallis and Futuna','WF','WLF');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (732,'Western Sahara','EH','ESH');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (887,'Yemen','YE','YEM');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (894,'Zambia','ZM','ZMB');
INSERT INTO `country_code` (`Numeric`,`Country`,`Alpha2`,`Alpha3`) VALUES (716,'Zimbabwe','ZW','ZWE');
